<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="56" started-at="2019-10-12T11:36:03 EDT" finished-at="2019-10-12T11:36:03 EDT">
    <groups>
    </groups>
    <test name="Default test" duration-ms="56" started-at="2019-10-12T11:36:03 EDT" finished-at="2019-10-12T11:36:03 EDT">
      <class name="tests.d_Basics_Post_XML">
        <test-method status="PASS" signature="setUp()[pri:0, instance:tests.d_Basics_Post_XML@646d64ab]" name="setUp" is-config="true" duration-ms="13" started-at="2019-10-12T11:36:03 EDT" finished-at="2019-10-12T11:36:03 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="Test()[pri:0, instance:tests.d_Basics_Post_XML@646d64ab]" name="Test" duration-ms="8" started-at="2019-10-12T11:36:03 EDT" finished-at="2019-10-12T11:36:03 EDT">
          <exception class="java.nio.file.NoSuchFileException">
            <message>
              <![CDATA[C:\Users\AAO8676\Documents\workspace-java-rest-api-automation\post_data.xml]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.nio.file.NoSuchFileException: C:\Users\AAO8676\Documents\workspace-java-rest-api-automation\post_data.xml
at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(Unknown Source)
at java.nio.file.Files.newByteChannel(Unknown Source)
at java.nio.file.Files.newByteChannel(Unknown Source)
at java.nio.file.Files.readAllBytes(Unknown Source)
at tests.d_Basics_Post_XML.GenerateStringFromResource(d_Basics_Post_XML.java:52)
at tests.d_Basics_Post_XML.Test(d_Basics_Post_XML.java:34)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.nio.file.NoSuchFileException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test -->
      </class> <!-- tests.d_Basics_Post_XML -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
